# Generated by Django 3.1.1 on 2021-07-08 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(max_length=200)),
                ('issue_id', models.CharField(blank=True, max_length=200, null=True)),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('processed_pages', models.IntegerField(blank=True, null=True)),
                ('processed_pages_repub', models.IntegerField(blank=True, null=True)),
                ('processed_pages_adv', models.IntegerField(blank=True, null=True)),
                ('via_repub2qa', models.BooleanField(default=False)),
                ('expected', models.DateField(blank=True, max_length=200, null=True)),
                ('client_received', models.DateTimeField(blank=True, null=True)),
                ('contractor_sent', models.DateTimeField(blank=True, null=True)),
                ('contractor_received', models.DateTimeField(blank=True, null=True)),
                ('client_sent', models.DateTimeField(blank=True, null=True)),
                ('sent_to', models.CharField(blank=True, max_length=200, null=True)),
                ('ftp_sent_to', models.CharField(blank=True, max_length=200, null=True)),
                ('invoice_client', models.CharField(blank=True, max_length=200, null=True)),
                ('invoice_contractor', models.CharField(blank=True, max_length=200, null=True)),
                ('ignore', models.BooleanField(default=False)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Unknown'), (1, 'To receive from client'), (2, 'To send to contractor'), (3, 'To receive from contractor'), (4, 'To send to client'), (5, 'Completed')], default=0)),
                ('mailstatus', models.PositiveSmallIntegerField(choices=[(20, 'Feed hold (awaiting release) notification sent.'), (0, 'No mails sent'), (1, '-3 day feed notification sent'), (2, '-2 day feed notification sent'), (3, '-1 day feed notification sent'), (4, '0 day feed notification sent'), (5, '0+30mins day feed notification sent'), (6, '0+120mins day feed notification sent'), (7, '+1 day feed notification sent'), (8, '+2 day feed notification sent'), (9, 'Notification sent feed will go on ignore list'), (10, 'Incorrect feed notification sent')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pubcode', models.CharField(max_length=200, unique=True)),
                ('publisher', models.CharField(max_length=200, unique=True)),
                ('live', models.BooleanField(default=False)),
                ('asin', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('repub', models.BooleanField(default=False)),
                ('amazon', models.BooleanField(default=False)),
                ('kindle', models.BooleanField(default=False)),
                ('pmg', models.BooleanField(default=False)),
                ('recipe', models.BooleanField(default=False)),
                ('puzzle', models.BooleanField(default=False)),
                ('extra_xml', models.BooleanField(default=False)),
                ('repub_new', models.BooleanField(default=False)),
                ('priority', models.BooleanField(default=False)),
                ('frequency', models.CharField(blank=True, max_length=200, null=True)),
                ('feed_time', models.TimeField(blank=True, null=True)),
                ('avg_page_count', models.IntegerField(blank=True, null=True)),
                ('contractor', models.CharField(blank=True, max_length=200, null=True)),
                ('ftp_client_in', models.CharField(blank=True, max_length=200, null=True)),
                ('ftp_client_out', models.CharField(blank=True, max_length=200, null=True)),
                ('ftp_contractor_in', models.CharField(blank=True, max_length=200, null=True)),
                ('ftp_contractor_out', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('internal', models.BooleanField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('edition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='extraction.edition')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extraction.publication')),
            ],
        ),
        migrations.AddField(
            model_name='edition',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extraction.publication'),
        ),
    ]
