# Generated by Django 3.1.1 on 2021-07-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0003_auto_20210708_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='publisher',
            field=models.CharField(max_length=200),
        ),
    ]
