# Generated by Django 3.1.1 on 2021-07-15 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0004_auto_20210708_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='ftp_sent_to',
            field=models.CharField(blank=True, default='Dummy Value', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='edition',
            name='invoice_client',
            field=models.CharField(blank=True, default='repubqa', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='edition',
            name='sent_to',
            field=models.CharField(blank=True, default='Dummy value', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='internal',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='note',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='asin',
            field=models.CharField(blank=True, default=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='contractor',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='frequency',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='ftp_client_in',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='ftp_client_out',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='ftp_contractor_in',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='ftp_contractor_out',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='priority',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='repub',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='repub_new',
            field=models.BooleanField(default=True),
        ),
    ]
